### ISSUE TITLE
The implementation details in the code.

### ISSUE THREAD

**Issue by SUNJIMENG** [google-research/xmcgan_image_generation#2]
Excuse me, line 216 in xmc_net.py,  "x = dense_fn(self.gf_dim * 16 * 4 * 4)(z)", which input the noise "z" into the linear layer. However, Table 7 in supp shows that the input is the concatenation of noise and reshaped condition. I wonder which one is right.

**Comment by kohjingyu** [comment]
Thanks for catching this. In this case, the code is correct - the input to the linear layer is just z. However, I believe there won't be a significant effect on results either way.
