### ISSUE TITLE
Question about the sentence embedding.

### ISSUE THREAD

**Issue by SUNJIMENG** [google-research/xmcgan_image_generation#3]
Excuse me, in your code, the sentence embedding is calculated by averaging the word embedding in the word_num dim. While, in BERT, the encoding corresponding to the '[CLS]' token can represent the whole sentence. Why not use this as sentence embedding?   Which one performs better?

**Comment by kohjingyu** [comment]
Sorry for the late reply. In our experiments we found that there was no difference, using either one produces similar results.
