### ISSUE TITLE
About the package libml

### ISSUE THREAD

**Issue by euyy** [google-research/xmcgan_image_generation#7]
Excuse me. I'm trying to run it. But now I encountered a problem. libml is not in the requirements.txt file. At the same time, when I installed it using pip, <from libml import input_pipline> reports an error <cannot import name 'input_pipeline' from 'libml' >. so what's the problem? What should I do?

**Comment by woctezuma** [comment]
https://github.com/google-research/xmcgan_image_generation/blob/edbff388c0c8e35af24d7bf8b7dbc4375729dcab/xmcgan/train_utils.py#L35

I think you don't want to install `libml` as it is included in the package.
cf. https://github.com/google-research/xmcgan_image_generation/tree/main/xmcgan/libml
